export const activeUsers = {
    getActiveUsersData() {
        return [
            {
                id: '1000',
                image: '/demo/images/avt/avt-001.png',
                phone: '08194423297',
                clientName: 'Diana King',
                businessName: 'Master Innovations',
                activeGig: 35,
                location: 'Charlotte',
                walletBalance: 4877,
                date: '2025-07-30T23:29:31.000Z',
                email: 'diana.king@example.com',
                rating: 4.7,
                bio: 'Committed to pushing boundaries and embracing future-oriented solutions.',
                projectDone: 138,
                bannerImage: '/demo/images/banner/banner-1.png',
                following: 4,
            },
            {
                id: '1001',
                image: '/demo/images/image1.png',
                phone: '08113888145',
                clientName: 'Mike Black',
                businessName: 'Digital Horizons',
                activeGig: 23,
                location: 'Portland',
                walletBalance: 1242,
                date: '2025-08-10T23:25:36.000Z',
                email: 'mike.black@example.com',
                rating: 1.9,
                bio: 'Turning next-generation ideas into reality with creativity and drive.',
                projectDone: 36,
                bannerImage: '/demo/images/banner/banner2.png',
                following: 34,
            },
            {
                id: '1002',
                image: '/demo/images/image2.png',
                phone: '08139621419',
                clientName: 'Thomas Chen',
                businessName: 'Solution Hub',
                activeGig: 10,
                location: 'Houston',
                walletBalance: 1866,
                date: '2025-07-07T06:01:09.000Z',
                email: 'thomas.chen@example.com',
                rating: 1.7,
                bio: 'Experienced professional with a passion for innovative solutions and client success.',
                projectDone: 178,
                bannerImage: '/demo/images/banner/banner3.png',
                following: 94,
            },
            {
                id: '1003',
                image: '/demo/images/image4.png',
                phone: '08161520318',
                clientName: 'Quinn Moore',
                businessName: 'Solution Innovations',
                activeGig: 63,
                location: 'Charlotte',
                walletBalance: 2025,
                date: '2025-07-21T03:03:22.000Z',
                email: 'quinn.moore@example.com',
                rating: 0.7,
                bio: 'Shaping the future with clear strategic vision and effective execution.',
                projectDone: 127,
                bannerImage: '/demo/images/banner/banner4.png',
                following: 394
            },
            {
                id: '1004',
                image: '/demo/images/image5.png',
                phone: '08189893646',
                clientName: 'Edward Brown',
                businessName: 'Peak Possibilities',
                activeGig: 28,
                location: 'Austin',
                walletBalance: 1825,
                date: '2025-08-28T09:09:17.000Z',
                email: 'edward.brown@example.com',
                rating: 4.3,
                bio: 'Leading the way in strategic innovations to revolutionize industries.',
                projectDone: 13,
                bannerImage: '/demo/images/banner/banner5.png',
                following: 520
            },
            {
                id: '1005',
                image: '/demo/images/image6.png',
                phone: '08190602457',
                clientName: 'Oscar Black',
                businessName: 'Synergy Minds',
                activeGig: 57,
                location: 'Atlanta',
                walletBalance: 2570,
                date: '2025-08-24T00:42:40.000Z',
                email: 'oscar.black@example.com',
                rating: 0.5,
                bio: 'Striving for excellence and elevating standards in every project.',
                projectDone: 44,
                bannerImage: '/demo/images/banner/banner6.png',
                following: 574
            },
            {
                id: '1006',
                image: '/demo/images/image7.png',
                phone: '08166189725',
                clientName: 'Bob Taylor',
                businessName: 'Future Catalysts',
                activeGig: 34,
                location: 'Atlanta',
                walletBalance: 1827,
                date: '2025-08-31T18:46:22.000Z',
                email: 'bob.taylor@example.com',
                rating: 2.9,
                bio: 'A collaborative leader focused on achieving peak performance through innovative thinking.',
                projectDone: 191,
                bannerImage: '/demo/images/banner/banner7.png',
                following: 862
            },
            {
                id: '1007',
                image: '/demo/images/image8.png',
                phone: '08125877898',
                clientName: 'Thomas King',
                businessName: 'Future Solutions',
                activeGig: 83,
                location: 'Houston',
                walletBalance: 4745,
                date: '2025-08-12T04:19:22.000Z',
                email: 'thomas.king@example.com',
                rating: 3.0,
                bio: 'Dedicated to delivering high-quality results and fostering strong client relationships.',
                projectDone: 162,
                bannerImage: '/demo/images/banner/banner8.png',
                following: 429
            },
            {
                id: '1008',
                image: '/demo/images/image9.png',
                phone: '08195371697',
                clientName: 'Diana Brown',
                businessName: 'Next Level Ventures',
                activeGig: 13,
                location: 'Phoenix',
                walletBalance: 3244,
                date: '2025-08-27T00:18:07.000Z',
                email: 'diana.brown@example.com',
                rating: 4.3,
                bio: 'Experienced professional with a passion for innovative solutions and client success.',
                projectDone: 59,
                bannerImage: '/demo/images/banner/banner9.png',
                following: 937
            },
            {
                id: '1009',
                image: '/demo/images/image10.png',
                phone: '08130015820',
                clientName: 'Sarah Wilson',
                businessName: 'Next Level Possibilities',
                activeGig: 14,
                location: 'Nashville',
                walletBalance: 2288,
                date: '2025-08-18T01:38:50.000Z',
                email: 'sarah.wilson@example.com',
                rating: 3.8,
                bio: 'Ready to take the next big leap, driving progress and innovation.',
                projectDone: 92,
                bannerImage: '/demo/images/banner/banner10.png',
                following: 369
            },
            {
                id: '1010',
                image: '/demo/images/image11.png',
                phone: '08127444303',
                clientName: 'Robert Moore',
                businessName: 'Creative Level',
                activeGig: 63,
                location: 'Philadelphia',
                walletBalance: 2754,
                date: '2025-08-25T01:26:00.000Z',
                email: 'robert.moore@example.com',
                rating: 2.0,
                bio: 'Shaping the future with clear strategic vision and effective execution.',
                projectDone: 128,
                bannerImage: '/demo/images/banner/banner11.png',
                following: 792
            },
            {
                id: '1011',
                image: '/demo/images/image12.png',
                phone: '08112115208',
                clientName: 'George King',
                businessName: 'Venture Innovations',
                activeGig: 39,
                location: 'Boston',
                walletBalance: 3586,
                date: '2025-07-18T09:08:44.000Z',
                email: 'george.king@example.com',
                rating: 2.9,
                bio: 'A visionary in digital transformation, always exploring new opportunities.',
                projectDone: 80,
                bannerImage: '/demo/images/banner/banner12.png',
                following: 969
            },
            {
                id: '1012',
                image: '/demo/images/image13.png',
                phone: '08108265730',
                clientName: 'Bob Black',
                businessName: 'Creative Leap',
                activeGig: 37,
                location: 'Atlanta',
                walletBalance: 2429,
                date: '2025-08-26T05:06:08.000Z',
                email: 'bob.black@example.com',
                rating: 1.9,
                bio: 'Expert in strategic planning and capital management for sustained growth.',
                projectDone: 119,
                bannerImage: '/demo/images/banner/banner13.png',
                following: 172
            },
            {
                id: '1013',
                image: '/demo/images/image14.png',
                phone: '08109804738',
                clientName: 'Edward King',
                businessName: 'Strategic Hub',
                activeGig: 10,
                location: 'Miami',
                walletBalance: 4063,
                date: '2025-07-08T00:47:22.000Z',
                email: 'edward.king@example.com',
                rating: 2.6,
                bio: 'Operating on a global scale to deliver exceptional results worldwide.',
                projectDone: 149,
                bannerImage: '/demo/images/banner/banner14.png',
                following: 945
            },
            {
                id: '1014',
                image: '/demo/images/image15.png',
                phone: '08198515510',
                clientName: 'Bob Hall',
                businessName: 'Master Forward',
                activeGig: 55,
                location: 'Charlotte',
                walletBalance: 1843,
                date: '2025-07-02T18:29:31.000Z',
                email: 'bob.hall@example.com',
                rating: 1.4,
                bio: 'Turning next-generation ideas into reality with creativity and drive.',
                projectDone: 113,
                bannerImage: '/demo/images/banner/banner15.png',
                following: 972
            },
            {
                id: '1015',
                image: '/demo/images/image16.png',
                phone: '08100783705',
                clientName: 'Jessica Black',
                businessName: 'Synergy Innovations',
                activeGig: 16,
                location: 'Miami',
                walletBalance: 623,
                date: '2025-08-27T07:50:26.000Z',
                email: 'jessica.black@example.com',
                rating: 2.3,
                bio: 'A strategic thinker with a keen eye for future possibilities and advancements.',
                projectDone: 188,
                bannerImage: '/demo/images/banner/banner16.png',
                following: 921
            },
            {
                id: '1016',
                image: '/demo/images/image17.png',
                phone: '08161385892',
                clientName: 'Quinn Miller',
                businessName: 'Peak Dreams',
                activeGig: 48,
                location: 'Raleigh',
                walletBalance: 4567,
                date: '2025-07-28T19:01:38.000Z',
                email: 'quinn.miller@example.com',
                rating: 3.1,
                bio: 'Striving for excellence and elevating standards in every project.',
                projectDone: 148,
                bannerImage: '/demo/images/banner/banner17.png',
                following: 405
            },
            {
                id: '1017',
                image: '/demo/images/image18.png',
                phone: '08114578356',
                clientName: 'Kevin Hall',
                businessName: 'Solution Performance',
                activeGig: 67,
                location: 'Los Angeles',
                walletBalance: 798,
                date: '2025-07-23T09:17:01.000Z',
                email: 'kevin.hall@example.com',
                rating: 4.6,
                bio: 'Committed to pushing boundaries and embracing future-oriented solutions.',
                projectDone: 5,
                bannerImage: '/demo/images/banner/banner18.png',
                following: 437
            },
            {
                id: '1018',
                image: '/demo/images/image19.png',
                phone: '08122532584',
                clientName: 'Laura Wilson',
                businessName: 'Peak Vision',
                activeGig: 43,
                location: 'Seattle',
                walletBalance: 1428,
                date: '2025-07-13T14:51:50.000Z',
                email: 'laura.wilson@example.com',
                rating: 3.2,
                bio: 'Striving for excellence and elevating standards in every project.',
                projectDone: 196,
                bannerImage: '/demo/images/banner/banner19.png',
                following: 656
            },
            {
                id: '1019',
                image: '/demo/images/image20.png',
                phone: '08153950966',
                clientName: 'Bob Wilson',
                businessName: 'Innovation Dreams',
                activeGig: 92,
                location: 'Philadelphia',
                walletBalance: 2037,
                date: '2025-07-22T13:56:54.000Z',
                email: 'bob.wilson@example.com',
                rating: 0.1,
                bio: 'A strategic thinker with a keen eye for future possibilities and advancements.',
                projectDone: 126,
                bannerImage: '/demo/images/banner/banner20.png',
                following: 41
            }
        ]
    },

    getActiveUsers() {
        return Promise.resolve(this.getActiveUsersData());
    },
}