export const activeTalents = {
    getActiveTalentsData() {
        return [
            {
                id: '1000',
                image: '/demo/images/image1.png',
                phone: '08184718888',
                clientName: 'George Wilson',
                activeGig: 18,
                location: 'Denver',
                walletBalance: 1497,
                date: '2025-07-25T21:42:30.000Z',
                email: 'george.wilson@example.com',
                rating: 1.5,
                bio: 'Committed to pushing boundaries and embracing future-oriented solutions.',
                projectDone: 103,
                bannerImage: '/demo/images/banner/banner1.png',
                following: 259,
                position: 'Super pro',
                followers: 127,
                portfolio: ['/demo/portfolio/image2.png', '/demo/portfolio/image20.png', '/demo/portfolio/image1.png'],
                career: 'Music Producer'
            },
            {
                id: '1001',
                image: '/demo/images/image2.png',
                phone: '08138365935',
                clientName: 'Bob Prince',
                activeGig: 41,
                location: 'Dallas',
                walletBalance: 2265,
                date: '2025-08-28T13:06:53.000Z',
                email: 'bob.prince@example.com',
                rating: 1.5,
                bio: 'Leading the way in strategic innovations to revolutionize industries.',
                projectDone: 196,
                bannerImage: '/demo/images/banner/banner2.png',
                following: 272,
                position: 'Top rated',
                followers: 586,
                portfolio: ['/demo/portfolio/image19.png', '/demo/portfolio/image5.png', '/demo/portfolio/image16.png', '/demo/portfolio/image17.png'],
                career: 'Sound Engineer'
            },
            {
                id: '1002',
                image: '/demo/images/image3.png',
                phone: '08133184852',
                clientName: 'Charlie Taylor',
                activeGig: 54,
                location: 'New York',
                walletBalance: 3637,
                date: '2025-07-11T10:40:03.000Z',
                email: 'charlie.taylor@example.com',
                rating: 1.4,
                bio: 'Committed to finding innovative solutions for complex challenges.',
                projectDone: 196,
                bannerImage: '/demo/images/banner/banner3.png',
                following: 317,
                position: 'Super pro',
                followers: 1105,
                portfolio: ['/demo/portfolio/image20.png', '/demo/portfolio/image2.png', '/demo/portfolio/image16.png'],
                career: 'Artist Manager'
            },
            {
                id: '1003',
                image: '/demo/images/image4.png',
                phone: '08154202157',
                clientName: 'Alice Chen',
                activeGig: 98,
                location: 'San Diego',
                walletBalance: 1453,
                date: '2025-08-18T08:10:53.000Z',
                email: 'alice.chen@example.com',
                rating: 1.4,
                bio: 'Bringing digital visions to life with creativity and precision.',
                projectDone: 101,
                bannerImage: '/demo/images/banner/banner4.png',
                following: 505,
                position: 'New Talent',
                followers: 4600,
                portfolio: ['/demo/portfolio/image14.png', '/demo/portfolio/image11.png', '/demo/portfolio/image16.png', '/demo/portfolio/image17.png'],
                career: 'Music Producer'
            },
            {
                id: '1004',
                image: '/demo/images/image5.png',
                phone: '08152702113',
                clientName: 'Charlie Prince',
                activeGig: 32,
                location: 'Charlotte',
                walletBalance: 4937,
                date: '2025-07-29T22:51:53.000Z',
                email: 'charlie.prince@example.com',
                rating: 3.7,
                bio: 'Ready to take the next big leap, driving progress and innovation.',
                projectDone: 133,
                bannerImage: '/demo/images/banner/banner5.png',
                following: 489,
                position: 'New Talent',
                followers: 3082,
                portfolio: ['/demo/portfolio/image14.png', '/demo/portfolio/image11.png', '/demo/portfolio/image4.png', '/demo/portfolio/image18.png'],
                career: 'Vocalist'
            },
            {
                id: '1005',
                image: '/demo/images/image6.png',
                phone: '08176655522',
                clientName: 'Diana Johnson',
                activeGig: 71,
                location: 'Atlanta',
                walletBalance: 1154,
                date: '2025-08-03T03:19:21.000Z',
                email: 'diana.johnson@example.com',
                rating: 0.8,
                bio: 'A collaborative leader focused on achieving peak performance through innovative thinking.',
                projectDone: 135,
                bannerImage: '/demo/images/banner/banner6.png',
                following: 6,
                position: 'Super pro',
                followers: 665,
                portfolio: ['/demo/portfolio/image20.png', '/demo/portfolio/image2.png', '/demo/portfolio/image13.png', '/demo/portfolio/image9.png'],
                career: 'Songwriter'
            },
            {
                id: '1006',
                image: '/demo/images/image7.png',
                phone: '08123287627',
                clientName: 'Kevin Wilson',
                activeGig: 63,
                location: 'New York',
                walletBalance: 1502,
                date: '2025-08-08T06:16:15.000Z',
                email: 'kevin.wilson@example.com',
                rating: 3.4,
                bio: 'Leading the way in strategic innovations to revolutionize industries.',
                projectDone: 1,
                bannerImage: '/demo/images/banner/banner7.png',
                following: 945,
                position: 'New Talent',
                followers: 1041,
                portfolio: ['/demo/portfolio/image13.png', '/demo/portfolio/image12.png', '/demo/portfolio/image10.png', '/demo/portfolio/image14.png', '/demo/portfolio/image11.png'],
                career: 'Session Musician'
            },
            {
                id: '1007',
                image: '/demo/images/image8.png',
                phone: '08103630269',
                clientName: 'Hannah Wilson',
                activeGig: 37,
                location: 'San Diego',
                walletBalance: 4304,
                date: '2025-07-23T10:04:01.000Z',
                email: 'hannah.wilson@example.com',
                rating: 1.3,
                bio: 'Committed to pushing boundaries and embracing future-oriented solutions.',
                projectDone: 145,
                bannerImage: '/demo/images/banner/banner8.png',
                following: 531,
                position: 'New Talent',
                followers: 4438,
                portfolio: ['/demo/portfolio/image2.png', '/demo/portfolio/image7.png', '/demo/portfolio/image16.png', '/demo/portfolio/image4.png'],
                career: 'Music Educator'
            },
            {
                id: '1008',
                image: '/demo/images/image9.png',
                phone: '08102381010',
                clientName: 'Bob Brown',
                activeGig: 81,
                location: 'Los Angeles',
                walletBalance: 3943,
                date: '2025-08-16T19:25:50.000Z',
                email: 'bob.brown@example.com',
                rating: 1.1,
                bio: 'A strategic thinker with a keen eye for future possibilities and advancements.',
                projectDone: 114,
                bannerImage: '/demo/images/banner/banner9.png',
                following: 989,
                position: 'New Talent',
                followers: 2459,
                portfolio: ['/demo/portfolio/image6.png', '/demo/portfolio/image7.png', '/demo/portfolio/image14.png'],
                career: 'Artist'
            },
            {
                id: '1009',
                image: '/demo/images/image10.png',
                phone: '08189108312',
                clientName: 'Quinn Brown',
                activeGig: 92,
                location: 'Boston',
                walletBalance: 3994,
                date: '2025-07-07T02:34:51.000Z',
                email: 'quinn.brown@example.com',
                rating: 2.1,
                bio: 'Ready to take the next big leap, driving progress and innovation.',
                projectDone: 166,
                bannerImage: '/demo/images/banner/banner10.png',
                following: 126,
                position: 'New Talent',
                followers: 1365,
                portfolio: ['/demo/portfolio/image11.png', '/demo/portfolio/image2.png', '/demo/portfolio/image17.png'],
                career: 'Music Journalist'
            },
            {
                id: '1010',
                image: '/demo/images/image11.png',
                phone: '08130648656',
                clientName: 'Diana Davis',
                activeGig: 14,
                location: 'Charlotte',
                walletBalance: 4929,
                date: '2025-07-13T05:13:17.000Z',
                email: 'diana.davis@example.com',
                rating: 1.8,
                bio: 'Committed to finding innovative solutions for complex challenges.',
                projectDone: 99,
                bannerImage: '/demo/images/banner/banner11.png',
                following: 483,
                position: 'New Talent',
                followers: 229,
                portfolio: ['/demo/portfolio/image16.png', '/demo/portfolio/image9.png', '/demo/portfolio/image3.png'],
                career: 'Music Producer'
            },
            {
                id: '1011',
                image: '/demo/images/image12.png',
                phone: '08191987406',
                clientName: 'Fiona Brown',
                activeGig: 17,
                location: 'Orlando',
                walletBalance: 1250,
                date: '2025-07-20T06:05:41.000Z',
                email: 'fiona.brown@example.com',
                rating: 1.5,
                bio: 'A strategic thinker with a keen eye for future possibilities and advancements.',
                projectDone: 97,
                bannerImage: '/demo/images/banner/banner12.png',
                following: 102,
                position: 'Top rated',
                followers: 4218,
                portfolio: ['/demo/portfolio/image7.png', '/demo/portfolio/image6.png', '/demo/portfolio/image10.png', '/demo/portfolio/image5.png'],
                career: 'Artist'
            },
            {
                id: '1012',
                image: '/demo/images/image13.png',
                phone: '08110455490',
                clientName: 'Hannah Smith',
                activeGig: 95,
                location: 'Chicago',
                walletBalance: 3384,
                date: '2025-07-04T11:09:32.000Z',
                email: 'hannah.smith@example.com',
                rating: 1.6,
                bio: 'Dedicated to delivering high-quality results and fostering strong client relationships.',
                projectDone: 99,
                bannerImage: '/demo/images/banner/banner13.png',
                following: 594,
                position: 'Top rated',
                followers: 2626,
                portfolio: ['/demo/portfolio/image14.png', '/demo/portfolio/image13.png', '/demo/portfolio/image4.png', '/demo/portfolio/image6.png', '/demo/portfolio/image6.png'],
                career: 'Sound Engineer'
            },
            {
                id: '1013',
                image: '/demo/images/image14.png',
                phone: '08134612622',
                clientName: 'Edward Moore',
                activeGig: 75,
                location: 'Austin',
                walletBalance: 507,
                date: '2025-08-21T10:20:02.000Z',
                email: 'edward.moore@example.com',
                rating: 0.1,
                bio: 'Ready to take the next big leap, driving progress and innovation.',
                projectDone: 185,
                bannerImage: '/demo/images/banner/banner14.png',
                following: 278,
                position: 'Top rated',
                followers: 311,
                portfolio: ['/demo/portfolio/image20.png', '/demo/portfolio/image15.png', '/demo/portfolio/image1.png'],
                career: 'Session Musician'
            },
            {
                id: '1014',
                image: '/demo/images/image15.png',
                phone: '08109349855',
                clientName: 'Patricia Smith',
                activeGig: 44,
                location: 'Seattle',
                walletBalance: 1435,
                date: '2025-08-26T15:52:35.000Z',
                email: 'patricia.smith@example.com',
                rating: 1.6,
                bio: 'A strategic thinker with a keen eye for future possibilities and advancements.',
                projectDone: 186,
                bannerImage: '/demo/images/banner/banner15.png',
                following: 930,
                position: 'Top rated',
                followers: 4748,
                portfolio: ['/demo/portfolio/image19.png', '/demo/portfolio/image19.png', '/demo/portfolio/image13.png', '/demo/portfolio/image12.png'],
                career: 'Concert Promoter'
            },
            {
                id: '1015',
                image: '/demo/images/image16.png',
                phone: '08157317656',
                clientName: 'Hannah Moore',
                activeGig: 40,
                location: 'Seattle',
                walletBalance: 3411,
                date: '2025-08-16T08:42:18.000Z',
                email: 'hannah.moore@example.com',
                rating: 1.9,
                bio: 'Shaping the future with clear strategic vision and effective execution.',
                projectDone: 122,
                bannerImage: '/demo/images/banner/banner16.png',
                following: 538,
                position: 'Super pro',
                followers: 1521,
                portfolio: ['/demo/portfolio/image13.png', '/demo/portfolio/image20.png', '/demo/portfolio/image9.png', '/demo/portfolio/image11.png', '/demo/portfolio/image12.png'],
                career: 'Music Producer'
            },
            {
                id: '1016',
                image: '/demo/images/image17.png',
                phone: '08194979780',
                clientName: 'George Brown',
                activeGig: 86,
                location: 'New York',
                walletBalance: 4344,
                date: '2025-07-28T13:18:00.000Z',
                email: 'george.brown@example.com',
                rating: 3.4,
                bio: 'Leading the way in strategic innovations to revolutionize industries.',
                projectDone: 192,
                bannerImage: '/demo/images/banner/banner17.png',
                following: 895,
                position: 'New Talent',
                followers: 3102,
                portfolio: ['/demo/portfolio/image18.png', '/demo/portfolio/image13.png', '/demo/portfolio/image9.png'],
                career: 'Artist'
            },
            {
                id: '1017',
                image: '/demo/images/image18.png',
                phone: '08105621429',
                clientName: 'Mike Davis',
                activeGig: 87,
                location: 'Las Vegas',
                walletBalance: 658,
                date: '2025-08-11T02:51:25.000Z',
                email: 'mike.davis@example.com',
                rating: 2.7,
                bio: 'Operating on a global scale to deliver exceptional results worldwide.',
                projectDone: 172,
                bannerImage: '/demo/images/banner/banner18.png',
                following: 396,
                position: 'New Talent',
                followers: 4438,
                portfolio: ['/demo/portfolio/image19.png', '/demo/portfolio/image13.png', '/demo/portfolio/image10.png', '/demo/portfolio/image1.png', '/demo/portfolio/image20.png'],
                career: 'Music Educator'
            },
            {
                id: '1018',
                image: '/demo/images/image19.png',
                phone: '08137291476',
                clientName: 'Hannah Brown',
                activeGig: 55,
                location: 'Charlotte',
                walletBalance: 1460,
                date: '2025-07-30T21:07:17.000Z',
                email: 'hannah.brown@example.com',
                rating: 1.0,
                bio: 'Ready to take the next big leap, driving progress and innovation.',
                projectDone: 64,
                bannerImage: '/demo/images/banner/banner19.png',
                following: 842,
                position: 'New Talent',
                followers: 3227,
                portfolio: ['/demo/portfolio/image18.png', '/demo/portfolio/image5.png', '/demo/portfolio/image19.png', '/demo/portfolio/image20.png', '/demo/portfolio/image13.png'],
                career: 'Music Journalist'
            },
            {
                id: '1019',
                image: '/demo/images/image20.png',
                phone: '08189719762',
                clientName: 'Sarah Chen',
                activeGig: 57,
                location: 'Denver',
                walletBalance: 3832,
                date: '2025-07-30T21:47:51.000Z',
                email: 'sarah.chen@example.com',
                rating: 4.9,
                bio: 'Mastering the art of vision-setting to guide impactful projects.',
                projectDone: 39,
                bannerImage: '/demo/images/banner/banner20.png',
                following: 195,
                position: 'Top rated',
                followers: 1618,
                portfolio: ['/demo/portfolio/image18.png', '/demo/portfolio/image4.png', '/demo/portfolio/image4.png', '/demo/portfolio/image11.png'],
                career: 'Vocalist'
            }
        ]
    },

    getActiveTalents() {
        return Promise.resolve(this.getActiveTalentsData());
    },
}